name: unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CPU tests
        run: |
          xcodebuild test \
            -project wisteria.xcodeproj \
            -scheme "tests" \
            -destination "platform=macOS,arch=arm64"

            